### PR TITLE
Initial conversion of MD hyperlinks to MediaWiki

### LINKED ISSUE #8: Automatically transform in-source links to in-wiki links
Hi

Thanks for developing **github-wiki-action**. There's a small problem with cross-links:

Steps to reproduce:

- create `docs/First.md` and `docs/Second.md`
- Add a link `[Second](./Second.md)` to the `First.md`
- The link works in GitHub UI
- Deploy Wiki
- The link does not work

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
[//]: # (Thanks for helping us out! Cache invalidation sucks, so your help is greatly appreciated!)

## Description

[//]: # (What're you proposing?)
Automatic conversion of hyperlinks to MediaWiki format

## Rationale

Fixes #8

### CODE REVIEW

**Comment by jcbhmr** [comment]
I don't know if this _should_ be in scope for this action? Is this GitHub action positioned as:

1. Your single-action one-stop-shop to deploy a folder to github wiki (handles build actions, possible rewriting, asset collection, etc.)
2. OR Just push a folder in git to a GitHub wiki

It's worth noting that this action is OK being a single-thing unix philosophy action!

```yml
- uses: Andrew-Chen-Wang/rewrite-markdown-links
  with:
    path: wiki
- run: git add -A && git commit --amend --no-edit
- uses: Andrew-Chen-Wang/github-wiki-action
```

This is kinda inline with what seems to be the convention of the official https://github.com/actions how they do things, and would be more modular overall

However this happens to pan out, I'd recommend updating the readme, the wiki, or somewhere with something like "Goals" or "Scope" to define _what you want the boundary to be_ so that if I ask "hey can I get this action to support compiling React apps to Markdown for my wiki?" you can point and say "no look for another action to preprocess" or "sure! that sounds like a good feature!"

**Comment by Andrew-Chen-Wang** [comment]
Yea I agree, splitting out would be nice.

**Comment by jcbhmr** [comment]
discussed in https://github.com/Andrew-Chen-Wang/github-wiki-action/issues/8#issuecomment-1550311999

gist is that I think we should do something like:

image

**Comment by jcbhmr** [comment]
I think this is "solved" with the addition of https://github.com/Andrew-Chen-Wang/github-wiki-action#preprocessing note?

**Pull request closed without merging**
