### PR TITLE
Add in-source to in-wiki link transformer

### LINKED ISSUE #8: Automatically transform in-source links to in-wiki links
Hi

Thanks for developing **github-wiki-action**. There's a small problem with cross-links:

Steps to reproduce:

- create `docs/First.md` and `docs/Second.md`
- Add a link `[Second](./Second.md)` to the `First.md`
- The link works in GitHub UI
- Deploy Wiki
- The link does not work

### PR DESCRIPTION
**Pull request by jcbhmr**
This also necessitated the transition to a more complex TypeScript/JavaScript environment instead of plain Bash. Why? To use the remark AST transformer of course!

closes #8

### CODE REVIEW

**Comment by jcbhmr** [comment]
There we go! I had fun getting those tests to show up XD
image

**Comment by jcbhmr** [comment]
Ok so at this point it works! All that's left is to add stuff to the readme

**Comment by jcbhmr** [comment]
Waiting to merge this for a bit to hopefully let @Andrew-Chen-Wang and/or @ribtoks see it

**Comment by Andrew-Chen-Wang** [comment]
nice work!

**Pull request merged**
